"""initial_tables

Revision ID: 12e698b6e589
Revises:
Create Date: 2026-03-20 16:31:53.043087

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "12e698b6e589"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "boxes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("xmin", sa.Float(), nullable=False),
        sa.Column("ymin", sa.Float(), nullable=False),
        sa.Column("xmax", sa.Float(), nullable=False),
        sa.Column("ymax", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "object_counts",
        sa.Column("object_class", sa.String(length=128), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("object_class"),
    )
    op.create_table(
        "predictions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("class_name", sa.String(length=128), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("box_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["box_id"],
            ["boxes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("predictions")
    op.drop_table("object_counts")
    op.drop_table("boxes")
    # ### end Alembic commands ###
